# Generated by Django 4.2.28 on 2026-09-02 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "admin_panel",
            "0019_order_is_paid_order_ref_id_order_transaction_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Waiter", "Waiter"),
                    ("Kitchen Staff", "Kitchen Staff"),
                ],
                default="Admin",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="cafe_logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_cafes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="cafe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="admin_panel.cafe",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cafe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="admin_panel.cafe",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cafe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="admin_panel.cafe",
            ),
        ),
    ]
