# Generated by Django 4.2.28 on 2026-09-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_panel",
            "0020_alter_profile_role_cafe_menuitem_cafe_order_cafe_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_cafes",
                to="admin_panel.cafe",
            ),
        ),
    ]
