# Generated by Django 4.2.28 on 2026-09-03 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0021_alter_cafe_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_cafes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="cafe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="admin_panel.cafe",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="cafe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="admin_panel.cafe",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="cafe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="admin_panel.cafe",
            ),
            preserve_default=False,
        ),
    ]
