# Generated by Django 4.2.28 on 2026-09-03 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0022_alter_cafe_owner_alter_menuitem_cafe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "qr_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="admin_panel.cafe",
                    ),
                ),
            ],
            options={
                "unique_together": {("cafe", "number")},
            },
        ),
    ]
