# Generated by Django 4.2.28 on 2026-09-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0024_order_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="served_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Awaiting Confirmation", "Awaiting Confirmation"),
                    ("Pending", "Pending"),
                    ("Preparing", "Preparing"),
                    ("Ready", "Ready"),
                    ("Served", "Served"),
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=25,
            ),
        ),
    ]
